# Jekyll configuration for Solidity Smart Contracts documentation
title: Lime Smart Contracts Documentation
description: Lime Smart Contracts Documentation
theme: jekyll-theme-cayman

# Site settings
lang: en
markdown: kramdown

# Custom settings for code highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# GitHub Pages auto-includes github-metadata plugin
github:
  is_project_page: true

  
# Exclude directories and files
exclude:
  - contracts/test
