name: Security Analysis

on: [push]

jobs:
  slither-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Slither
        run: pip install slither-analyzer
      - name: Run Slither
        run: slither .
